import { useRouter } from 'next/router'
import axios from "../api/authApi";
import { Navbar } from '@components';
import { useEffect } from 'react';
import { useState } from 'react';
import Calendar from '../../components/calendar';
import Head from 'next/head';


const Post = () => {
    const router = useRouter()
    const { owner_id } = router.query
    const [data, setData] = useState(null)
    const [userData, setUserData] = useState(null)
    const BOOKNOW_URL = `/court/booknow/${data?._id}`;
    const USER_URL = `${router.query.user_id}`


    useEffect(() => {
        const getUsers = async () => {
            if (router.query.user_id) {
                const response = await axios.get(USER_URL);
                setUserData(response)
            }
        };
        getUsers();
    }, [router.query.user_id])



    const handleSubmit = async () => {
        try {
            delete data._id
            data.date = dateTime
            const response = await axios.post(
                BOOKNOW_URL,
                JSON.stringify(data),
                {
                    headers: {
                        "Content-Type": "application/json",
                    },
                    withCredentials: true,
                }
            );
            // response.data.id && setSuccessMsg(response.data.id)
        } catch (err) {
            console.log(err, "error");
        }
    }

    useEffect(() => {
        // fetch data
        const dataFetch = async () => {
            const data =
                await axios.get(
                    `/court/${owner_id}`

                );
            data?.data && setData(data?.data.data[0])
        };

        dataFetch();
    }, [owner_id]);
    return (
        <div className='w-full'>
            <Navbar />
            <Head>
                <title>Arena | Confirmation Page</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='flex flex-col items-center mt-16 gap-10'>
                <div className=' flex flex-col items-center bg-white outline-gray shadow-sm px-4 py-2 font-light text-[#434342] italic w-3/5 rounded-3xl text-center'>

                    <div class="md:flex md:items-center mb-6">
                        <div class="md:w-1/3">
                            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-full-name">
                                Full Name
                            </label>
                        </div>
                        <div class="md:w-2/3">
                            <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-full-name" type="text" value="Jane Doe" />
                        </div>
                    </div>
                    <div class="md:flex md:items-center mb-6">
                        <div class="md:w-1/3">
                            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                                Password
                            </label>
                        </div>
                        <div class="md:w-2/3">
                            <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" id="inline-password" type="password" placeholder="******************" />
                        </div>
                    </div>
                    <div class="md:flex md:items-center mb-6">

                    </div>
                    <div class="md:flex md:items-center">
                        <div class="md:w-1/3"></div>
                        <div class="md:w-2/3">
                            <button class="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded" type="button">
                                Sign Up
                            </button>
                        </div>
                    </div>
                </div>

                <button type="button" className=" w-max	rounded-3xl block w-full bg-green-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Check booking status</button>
            </main>
        </div>
    );
}

export default Post