import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import { ROUTES } from '@constants';
import { Navbar } from '@components';
import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] });

export default function Confirmation() {
    return (
        <>
            <div className='w-full'>
                <Navbar />
                <Head>
                    <title>Arena | Confirmation Page</title>
                    <meta name='description' content='Generated by create next app' />
                    <meta name='viewport' content='width=device-width, initial-scale=1' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <main>
                    <h1>
                        confirmation page
                    </h1>
                   <center> <div className="mt-10 content-center justify-center">
                        <button type="submit" className="block w-full rounded-md bg-green-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Check booking status</button>
                    </div></center>
                </main>
            </div>
        </>
    );
}
