import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import { ROUTES } from '@constants';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();
  const handleClick = (e) => {
    e.preventDefault();
    router.push(ROUTES.register);
  };
  const handleCourtList = (e) => {
    e.preventDefault();
    router.push(ROUTES.courtList);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-blue-600 text-xl'>Welcome to Arena</h1>
        <button type='button' onClick={handleClick}>
          Register
        </button><br/>
        <button type='button' onClick={handleCourtList}>
          Court
        </button>
      </main>
    </>
  );
}
