import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { ROUTES } from "@constants";
import { Navbar } from "@components";
import MainLayout from "@components/layout/mainlayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const handleClick = (e) => {
    e.preventDefault();
    router.push(ROUTES.register);
  };
  const handleCourtList = (e) => {
    e.preventDefault();
    router.push(ROUTES.courtList);
  };
  const handleLogin = (e) => {
    e.preventDefault();
    router.push(ROUTES.login);
  };

  return (
    <>
      <Head>
        <title>Arena</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className="w-full">
        {/* <Navbar /> */}

        <main>
          <div className="flex items-center justify-between 	...">
            <div className="pl-10 w-1/2 flex flex-col justify-between min-h-500">
              <div className="w-1/2">
                <h1 className=" text-2xl w-1/2 text-[#434342] italic">
                  Draw Back, serve and hit it across the net.
                </h1>
              </div>

              <div className="flex flex-row items-center justify-between w-1/2 ... ">
                <button className="py-2  text-xl text-black text-[#434342] ">
                  Get Started
                </button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M15.91 11.672a.375.375 0 010 .656l-5.603 3.113a.375.375 0 01-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112z"
                  />
                </svg>
              </div>

              <div className="flex flex-row gap-10">
                <div className="w-1/2 flex flex-col justify-between">
                  <h1 className=" text-sm text-[#434342] font-semibold	">
                    There will be many obstacles in the pursuit of your dreams.
                    I had long hours of training, balancing studies and
                    badminton.
                  </h1>
                  <p>-P.V. Sindhu</p>
                </div>

                <div className="w-1/2 flex flex-col justify-between	">
                  <h1 className=" text-sm text-[#434342] font-semibold	">
                    I love winning more than i love playing badminton. Winnig is
                    everything
                  </h1>
                  <p>-Saina Nehwal</p>
                </div>
              </div>
            </div>
            <div className="w-1/2">
              <img
                className="rounded-t-lg  ..."
                src="https://i.ibb.co/185nRMc/Group-1-1.png"
                alt="splash image missing"
              />
            </div>
          </div>
        </main>
      </div>
      {/* <main>
        <h1 className='text-blue-600 text-xl'>Welcome to Arena</h1>
        <button type='button' onClick={handleClick}>
          Register
        </button><br/>
        <button type='button' onClick={handleLogin}>
          Login
        </button><br/>
        <button type='button' onClick={handleCourtList}>
          Court
        </button>
      </main> */}
    </>
  );
}

Home.getLayout = MainLayout

export async function getServerSideProps(context) {
  /**
   * check for session details here
   */

  if (!session) {
		return {
			redirect: {
				destination: '/login',
			},
		}
	}
  
	return {
		props: {},
	}
}