import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import { ROUTES } from '@constants';
import { Navbar } from '@components';
import { useState } from 'react';


export default function BookNow() {
    const router = useRouter();
    const { owner_id } = router.query
    const REGISTER_URL = "/owner/signup";
    useEffect(() => {
        // fetch data
        const dataFetch = async () => {
            const data =
                await axios.get(
                    `/court/${owner_id}`
                );
            data.data && setData(data?.data.data[0])
        };
        dataFetch();
    }, [owner_id]);
    return (
        <>
            <div className='w-full'>
                <Navbar />
                <Head>
                    <title>Create Next App</title>
                    <meta name='description' content='Generated by create next app' />
                    <meta name='viewport' content='width=device-width, initial-scale=1' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <main>
                    <form action="#" method="POST" className="mx-auto mt-16 max-w-xl sm:mt-20">
                       <div className="grid grid-cols-1 gap-y-6 gap-x-8 sm:grid-cols-2">
                        <p>sdfghj</p>
                       </div>
                    </form>
                </main>
            </div>
        </>
    );
}
