import Head from 'next/head';
import { Navbar } from '@components';
import { useRouter } from 'next/router';
export default function Home() {
    const router = useRouter()
    const { owner_id } = router.query
    return (
        <>
            <div className='w-full'>
                <Navbar />
                <Head>
                    <title>Owner Home</title>
                    <meta name='description' content='Generated by create next app' />
                    <meta name='viewport' content='width=device-width, initial-scale=1' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <main>
                    <h3 onClick={() => router.push(`/owner/AddCourt/${owner_id}`)}>Add court</h3 >
                    <h3 onClick={() => router.push(`/owner/Slot/${owner_id}`)}>Choose slot</h3 >
                    <h3 >Payment details</h3>
                </main>
            </div>
        </>
    );
}
