import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import { ROUTES } from '@constants';
import axios from "../api/authApi"
import { Navbar } from '@components';
import { useEffect, useState } from 'react';
import { validateCourt } from '../../components/validation/validate';
export default function AddCourt() {
    const intialValues = { courtName: "", location: "", address: "", sports: "Badminton", facility:"",price:"" };
    const router = useRouter();
    const [formValues, setFormValues] = useState(intialValues);
    // const [slot, setSlot] = useState(false)
    const [formErrors, setFormErrors] = useState({});
    const [successMsg, setSuccessMsg] = useState(null)
    const [isSubmitting, setIsSubmitting] = useState(false);
    const ADDCOURT_URL = "/court/addcourt";
    const [fromTime, setFromTime] = useState([1]);
    const [toTime, setToTime] = useState([1]);
    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormValues({ ...formValues, [name]: value });
    };
    useEffect(()=>{
        if(successMsg === "court added"){
            router.push("/")
        }
    })
    // useEffect(() => {
    //     const arr = [];
    //     for (let i = 1; i <= 12; i++) {
    //         arr.push(i);
    //     }
    //     setFromTime(arr);
    // }, [])
    // useEffect(() => {
    //     const arr = [];
    //     for (let i = formValues.from; i <= 24; i++) {
    //         arr.push(i);
    //     }
    //     setToTime(arr)
    // }, [formValues.from])
    const handleSubmit = async (e) => {
        e.preventDefault();
          try {
            const response = await axios.post(
                ADDCOURT_URL,
                JSON.stringify(formValues),
                {
                    headers: {
                        "Content-Type": "application/json",
                    },
                    withCredentials: true,
                }
            );
            console.log(response,"res...from api");
            response.data.id && setSuccessMsg("court added")
        } catch (err) {
            console.log(err, "errr");
        }
    }
    console.log(formErrors,"formErrors......");
    return (
        <>
            <div className='w-full'>
                <Navbar />
                <Head>
                    <title>Arena | Add court</title>
                    <meta name='description' content='Generated by create next app' />
                    <meta name='viewport' content='width=device-width, initial-scale=1' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <main>
                    <form action="#" method="POST" onSubmit={handleSubmit} className="mx-auto mt-16 max-w-xl sm:mt-20">
                        <div className="grid grid-cols-1 gap-y-6 gap-x-8 sm:grid-cols-2">
                            <div className="sm:col-span-2">
                                <label className="block text-sm font-semibold leading-6 text-gray-900">Badminton court</label>
                                <div className="mt-2.5">
                                    <input type="text" name="courtName" id="courtName" onChange={handleChange} className="block w-full rounded-md border-0 py-2 px-3.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" required />
                                </div>
                            </div>
                            <div>
                                <label className="block text-sm font-semibold leading-6 text-gray-900">Location</label>
                                <select name="location" onChange={handleChange} required>
                                    <option value="" selected disabled >Select Location</option>

                                    <option value="chennai" >Chennai</option>
                                    <option value="bangalore">Bangalore</option>
                                </select></div>
                            <div className="sm:col-span-2">
                                <label className="block text-sm font-semibold leading-6 text-gray-900">Address</label>
                                <div className="mt-2.5">
                                    <textarea name="address" id="address" onChange={handleChange} className="block w-full rounded-md border-0 py-2 px-3.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" required></textarea>
                                </div>
                            </div>
                            <div className="sm:col-span-2">
                                <label className="block text-sm font-semibold leading-6 text-gray-900">Sports</label>
                                <div className="mt-2.5">
                                    <input type="text" name="sports" value="Badminton" id="sports" className="block w-full rounded-md border-0 py-2 px-3.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" required/>
                                </div>
                            </div>
                            <div className="sm:col-span-2">
                                <label className="block text-sm font-semibold leading-6 text-gray-900">Price</label>
                                <div className=" mt-2.5">
                                    <input type="number" onChange={handleChange} name="price" id="price" className="block w-full rounded-md border-0 py-2 px-3.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" required />
                                </div>
                            </div>
                            <div>
                                <label className="block text-sm font-semibold leading-6 text-gray-900">Facility</label>
                                <select name="facility" onChange={handleChange} required>
                                    <option value="" selected disabled >Select facility</option>

                                    <option value="AC" >AC</option>
                                    <option value="Non AC">Non AC</option>
                                </select></div>
                            {/* {slot != true && (<div className="mt-10">
                                <div onClick={() => setSlot(true)} className="block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" >Select slot</div>
                            </div>)}


                            {slot && (<> <div>
                                <label className="block text-sm font-semibold leading-6 text-gray-900">TIME</label>

                                <label className="block text-sm font-semibold leading-6 text-gray-900">From</label>
                                <select name="from" onChange={handleChange}>
                                    {fromTime?.map((i) => {
                                        return (
                                            <option value={i}>{i}</option>
                                        )
                                    })}

                                </select>
                            </div>

                                <div>
                                    <label className="block text-sm font-semibold leading-6 text-gray-900">To</label>
                                    <select name="to" onChange={handleChange}>
                                        {toTime?.map((i) => {
                                            return (
                                                <option value={i}>{i}</option>
                                            )
                                        })}

                                    </select>
                                </div>
                            </>)} */}
                            <div className="mt-10 content-center justify-center">
                                <button type="submit" className="block w-full rounded-md bg-green-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-green-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600">Submit</button>
                            </div>
                        </div>
                    </form>
                </main>
            </div>
        </>
    );
}
