import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import { ROUTES } from '@constants';
import axios from "../api/authApi"
import { Navbar } from '@components';
import { useEffect, useState } from 'react';
import { validateCourt } from '../../components/validation/validate';
export default function AddSlot() {
    const intialValues = { courtName: "", location: "", address: "", sports: "Badminton", facility:"",price:"" };
    const router = useRouter();
    const [formValues, setFormValues] = useState(intialValues);
    // const [slot, setSlot] = useState(false)
    const [formErrors, setFormErrors] = useState({});
    const [successMsg, setSuccessMsg] = useState(null)
    const [isSubmitting, setIsSubmitting] = useState(false);
    const ADDCOURT_URL = "/court/addcourt";
    const [fromTime, setFromTime] = useState([1]);
    const [toTime, setToTime] = useState([1]);
    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormValues({ ...formValues, [name]: value });
    };
    useEffect(()=>{
        if(successMsg === "court added"){
            router.push("/")
        }
    })
    // useEffect(() => {
    //     const arr = [];
    //     for (let i = 1; i <= 12; i++) {
    //         arr.push(i);
    //     }
    //     setFromTime(arr);
    // }, [])
    // useEffect(() => {
    //     const arr = [];
    //     for (let i = formValues.from; i <= 24; i++) {
    //         arr.push(i);
    //     }
    //     setToTime(arr)
    // }, [formValues.from])
    // const handleSubmit = async (e) => {
    //     e.preventDefault();
    //       try {
    //         const response = await axios.post(
    //             ADDCOURT_URL,
    //             JSON.stringify(formValues),
    //             {
    //                 headers: {
    //                     "Content-Type": "application/json",
    //                 },
    //                 withCredentials: true,
    //             }
    //         );
    //         console.log(response,"res...from api");
    //         response.data.id && setSuccessMsg("court added")
    //     } catch (err) {
    //         console.log(err, "errr");
    //     }
    // }
    return (
        <>
            <div className='w-full'>
                <Navbar />
                <Head>
                    <title>Arena | Add slot</title>
                    <meta name='description' content='Generated by create next app' />
                    <meta name='viewport' content='width=device-width, initial-scale=1' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <main>
                    <form action="#" method="POST" onSubmit={handleSubmit} className="mx-auto mt-16 max-w-xl sm:mt-20">
                       <div>
                        
                       </div>
                    </form>
                </main>
            </div>
        </>
    );
}
